stages:
  build:
  - definition: MavenRune
    mavenHome: ~/.m2
    stages: clean install
    version: 3.5.0-jdk-8-slim
definitions:
- "https://raw.githubusercontent.com/sygaldry/sygaldry-runes/feature/writeRuneDefsFile/rune-definitions.yaml"
