stages:
  build:
  - definition: MavenRune
    mavenHome: ~/.m2
    stages: clean install
    version: 3.5.0-jdk-8-slim
  - definition: DockerRune
    version: stable
    command: build
    args: "-t docker.io/sygaldry-demos/springboot:latest ."
  publish:
  - definition: DockerRune
    version: stable
    command: push
    dockerConfigPath: ~/.docker/config-sygaldry.json
    args: "docker.io/sygaldry-demos/springboot:latest"
definitions:
- "https://raw.githubusercontent.com/sygaldry/sygaldry-runes/feature/writeRuneDefsFile/rune-definitions.yaml"
